steps:
  - uses: actions/checkout@v1
  - uses: rahul-deepsource/pyaction@1.4.0
    with:
      python-root-list: "fserver/"
      use-pycodestyle: false
      use-mypy: false
      use-vulture: true
      extra-pylint-options: "--output-format="colorized"