version: '3'

services:

  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev-use-only
    ports:
      - 5432:5432

  backend:
    build:
      context: ./fserver
    ports:
      - '8000:8000'
    volumes:
      - ./fserver:/code
    command: sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    environment:
      - DB_HOST=db
      - DB_NAME=chat
      - DB_USER=postgres
      - DB_PASS=dev-use-only
    depends_on:
      - db
  
  frontend:
    build:
      context: ./client
      target: dev
    restart: unless-stopped
    command: sh -c 'ls -a && npm run start'
    ports:
      - 3000:3000
    volumes:
      - ./client:/code
      - ./client/node_modules:/code/node_modules

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
  
